blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions
    url: https://github.com/sudip-mondal-2002/Amplitron/discussions
    about: Please ask general questions or seek help in our Discussions forum.
